---
# tasks file for extras

- name: Get Git Files
  become: False
  git:
    repo: https://github.com/SachinMaharana/ceph-ansible-custom.git
    dest: ~/ceph-csi
  when: inventory_hostname == "master-0"

# - name: Check Ceph
#   debug:
#     msg: "{{ ceph_status.stdout_lines }}"
#   delegate_to: "{{ groups[mons][0] }}"
#   run_once: true
#   when: not ceph_status.failed

- name: get ceph status from the first monitor
  command: ceph mon dump
  register: ceph_status
  changed_when: false
  delegate_to: "{{ groups.mons[0] }}"
  run_once: true

- name: "show ceph status for cluster ceph"
  debug:
    msg: "{{ ceph_status.stdout_lines }}"
  delegate_to: "{{ groups.mons[0] }}"
  run_once: true

- name: write to master node
  copy:
    content: "{{ ceph_status.stdout_lines }}"
    dest: ~/ceph
  become: False
  delegate_to: "{{ groups.masters[0] }}"
  run_once: true

- name: get kubectl completions
  get_url:
    url: https://raw.githubusercontent.com/ahmetb/kubectl-alias/master/.kubectl_aliases
    dest: ~/.kubectl_aliases
  become: False
  delegate_to: "{{ groups.masters[0] }}"
  run_once: true

- name: Insert a line at the end of a file.
  lineinfile:
    dest: ~/.bashrc
    line: "[ -f ~/.kubectl_aliases ] && source ~/.kubectl_aliases"
  become: False
  delegate_to: "{{ groups.masters[0] }}"
  run_once: true
