---
# tasks file for extras

- name: Get Git Files
  become: False
  git:
    repo: https://github.com/SachinMaharana/ceph-ansible-custom.git
    dest: ~/deploy
  when: inventory_hostname == "master-0"

# - name: mkdir repo
#   become: False
#   command: "{{ item }}"
#   with_items:
#     - mkdir -p ~/csi
#   when: inventory_hostname == "master-0"

- name: Copy repo
  become: False
  copy:
    src: ~/deploy/ceph-csi/
    dest: ~/csi
    remote_src: true
  when: inventory_hostname == "master-0"

- name: get ceph status from the first monitor
  command: "{{ item }}"
  register: ceph_status
  changed_when: false
  delegate_to: "{{ groups.mons[0] }}"
  run_once: true
  with_items:
    - ceph mon dump
    - ceph osd pool create kube 64 64
    - ceph osd pool get kube all
    - rbd pool init kube
    - ceph --cluster ceph auth get-or-create client.kubeuser mon 'allow r' osd 'allow rwx pool=kube'
    - ceph auth get-or-create client.kubeuser

- name: "show ceph status for cluster ceph"
  debug:
    msg: "{{ ceph_status.results[0].stdout_lines }}"
  delegate_to: "{{ groups.mons[0] }}"
  run_once: true

- name: write status to master node
  copy:
    content: "{{ ceph_status.results[0].stdout_lines }}"
    dest: ~/ceph
  become: False
  delegate_to: "{{ groups.masters[0] }}"
  run_once: true

- name: write auth to master node
  copy:
    content: "{{ ceph_status.results[5].stdout_lines }}"
    dest: ~/auth
  become: False
  delegate_to: "{{ groups.masters[0] }}"
  run_once: true

- name: get kubectl completions
  get_url:
    url: https://raw.githubusercontent.com/ahmetb/kubectl-alias/master/.kubectl_aliases
    dest: ~/.kubectl_aliases
  become: False
  delegate_to: "{{ groups.masters[0] }}"
  run_once: true

- name: Insert kubectl completions
  lineinfile:
    dest: ~/.bashrc
    line: "[ -f ~/.kubectl_aliases ] && source ~/.kubectl_aliases"
  become: False
  delegate_to: "{{ groups.masters[0] }}"
  run_once: true

- name: Copy binary
  copy:
    src: k9s
    dest: /usr/local/bin
    mode: a+x
  delegate_to: "{{ groups.masters[0] }}"
  run_once: true
